---

- name: Download OpenVPN GPG key
  get_url:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    dest: /tmp/openvpn.gpg
  when: openvpn_use_external_repo

- name: Add OpenVPN repo GPG key (Debian)
  apt_key:
    file: /tmp/openvpn.gpg
    id: E158C569
    state: present
  when: openvpn_use_external_repo

- name: Remove old OpenVPN repo sources (Debian)
  apt_repository:
    filename: openvpn
    repo: deb http://swupdate.openvpn.net/apt {{ ansible_lsb.codename }} main
    state: absent
  when: openvpn_use_external_repo
  register: openvpn_repo_action

- name: Add new OpenVPN repo sources (Debian)
  apt_repository:
    filename: openvpn
    repo: deb http://build.openvpn.net/debian/openvpn/release/2.3 {{ ansible_lsb.codename }} main
    state: present
  when: openvpn_use_external_repo
  register: openvpn_repo_action


- name: Install requirements (Debian)
  apt: name={{item}}
  with_items: [openvpn, udev, openssl, zip]

- name: Update OpenVPN (Debian)
  apt: name=openvpn state=latest
  when: openvpn_use_external_repo and openvpn_repo_action.changed

- name: Install dependencies (Debian)
  apt: name={{item}}
  when: openvpn_use_pam_users|default(false)
  with_items: [libpam-pwdfile, python-passlib]

- name: Install easy-rsa package (Debian)
  apt: name=easy-rsa
  when: openvpn_use_system_easyrsa

- name: Install LDAP dependencies (Debian)
  apt: name=openvpn-auth-ldap force=yes
  when: openvpn_use_ldap

- name: Install bridge dependencies (Debian)
  apt: name={{item}}
  when: openvpn_bridge
  with_items: [bridge-utils]
