---

- name: openvpn restart
  service: name={{openvpn_service}} state=reloaded
  when: not openvpn_only_keys

- name: openvpn pack clients
  command: >
    zip -ju {{item}}.zip {{item}}.crt {{item}}.key {{item}}.ovpn
    ca.crt {{openvpn_tls_key if openvpn_tls_auth else ''}}
  args:
    chdir: "{{openvpn_keydir}}"
  with_items: "{{openvpn_clients}}"
  register: openvpn_pack_clients
  changed_when: openvpn_pack_clients.rc != 12
  failed_when: openvpn_pack_clients.rc not in [0, 12]
